// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer Vite-provided env vars (Vercel/Local) and fall back to existing values
const SUPABASE_URL = (import.meta as any).env?.VITE_SUPABASE_URL ?? "https://ifhrsaszgrzbpfbsvrpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmaHJzYXN6Z3J6YnBmYnN2cnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTExMzksImV4cCI6MjA2OTU2NzEzOX0.eP_8doOl1Y4YLLkx_yCda9gpgdOoY6jCHJzoUclqTvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});